apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals: 
  chartHome: ../../charts/


helmCharts:
  - name: hello-world
    version: 1.0.0
    releaseName: hello-world-1
    valuesFile: values.yaml