apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test

resources: 
  - ../base-manifests/helloworld-1
  - ../base-manifests/helloworld-2


patches: 
  - path: helloworld-1/change-image.yaml
  - path: helloworld-2/change-image.yaml